### ISSUE TITLE
Oooooo 💓 all the screenshots in your readme!

### ISSUE THREAD

**Issue by PySimpleGUI** [jgmarquesm/Python#1]
Very nice readme!

Congratulations on making your first GUI-based program and it using multiple windows.  

![image](https://user-images.githubusercontent.com/46163555/172239224-6ada9686-335b-4872-a30b-551b6734ff75.png)

I like it!  I really like that you're proud of what you built and want to share it with the world.  Great spirit, great attitude!

Keep on building!  You're on a roll!!

**Comment by jgmarquesm** [comment]
Thank you very much. I discovered PySimpleGUI a few days ago, and I loved it!
YEAH! I'm proud of my first (of many) project using your Framework!
